extends Node

const TERRAIN_COLLISION_LAYER= 1
const PLAYER_COLLISION_LAYER= 2
const MOB_COLLISION_LAYER= 3
const PROJECTILE_COLLISION_LAYER= 6
const HURTBOX_COLLISION_LAYER= 7
const SOLID_ENTITY_COLLISION_LAYER= 8

const HEALT_COMPONENT_NODE= "Health Component"

var game: Game
